Keep the refresh token in cache if not changed
KaiJewson/aspotify pull request #5
Opened 2020-11-12 18:53 UTC by xvello

When using the Authorization code flow (manually provided refresh_token), calling `Client.access_token` will remove the refresh token from the cache, meaning it cannot be used to retrieve another access token after that one expired.

I think the issue also rises after 2 hours if we go through `Client.redirected` (not providing a token, asking for user action): we'll be able to refresh the access token once, but not twice (the first refresh will clear out the refresh_token from the cache).

This PR holds the following changes:

- Add get_artist example to make sure I didn't break the client credentials flow
- Add a `TokenRequest` enum to materialize the request body more expressively than tuples
- Fix `access_token` to re-inject an existing refresh_token value if the response does not have one

I am pretty new to Rust, please nitpick what you'd like to adjust.

2020-11-13 17:30 UTC, KaiJewson requested changes
Thanks so much for noticing this! Just a few small issues and it can be merged :).

2020-11-13 17:30 UTC, KaiJewson commented on src/lib.rs
> +use std::borrow::Borrow;
Move this to the group of `std` imports above this, I think it makes it cleaner.

2020-11-13 17:30 UTC, KaiJewson commented on src/lib.rs
> +                code: code.borrow(),
`Deref` is probably more appropriate here, as it's the method mentioned in the `Cow` docs and it avoids confusion with other methods named `borrow`.

2020-11-13 17:30 UTC, KaiJewson commented on src/lib.rs
> +                        .await?
Moving this `.await?` to the call on `token_request` avoids having to use `map_ok`; you can just use normal control flow.

2020-11-13 17:30 UTC, KaiJewson commented on src/lib.rs
> +                            token.refresh_token = Some(refresh_token.clone());
You can avoid this clone by `std::mem::take`ing `cache.refresh_token` before this.

2020-11-14 16:39 UTC, xvello commented
Thanks a lot for the review! Changes implemented and manually tested with the examples

2020-11-14 16:42 UTC, merged